### ISSUE TITLE
Code Analysis warning for SDL_bool

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#308]
We are currently getting a Code Analysis warning from an external header file:
> C:\Users\User\source\repos\vcpkg\installed\x64-windows\include\SDL2\SDL_rect.h(102): warning C26812: The enum type 'SDL_bool' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).

As this is an external header file, it's not one we would want to fix ourselves. Additionally, the header file is meant for C compatibility, and the warning only makes sense for C++.

It would be nice to silence the warning for this file (or any external header files), while still allowing for warnings without our project source. It seems this is possible using a `CAExcludePath` setting in the project file.

References:
[No option to suppress C++ code analysis warning C26812 (new in MSVC 2019 16.3.0 preview 3)](https://developercommunity.visualstudio.com/content/problem/724840/no-option-to-suppress-c-code-analysis-warning-c268.html)
[Add target property to set CAExcludePath in Visual Studio projects](https://gitlab.kitware.com/cmake/cmake/issues/19682)
[Enable Visual Studio's C++ Core Check analysis only on project files?](https://stackoverflow.com/questions/49581167/enable-visual-studios-c-core-check-analysis-only-on-project-files)

That last one mentions `vcpkg` specifically.

**Comment by cugone** [comment]
The issue's been fixed as of last week and is upcoming in 16.6....Only took them 6 months plus the time to actually release 16.6.

**Comment by DanRStevens** [comment]
I still don't see it yet. Latest update check still shows 16.5 as current.

Any details on what exactly was fixed? I noticed we have a use of `SDL_bool` within our code, which generates a warning once the header warning is suppressed.

**Comment by cugone** [comment]
Post fourth from the bottom on the developer community page: https://developercommunity.visualstudio.com/content/problem/724840/no-option-to-suppress-c-code-analysis-warning-c268.html?childToView=965908#comment-965908

You may have to manually re-request the page after loading it. The link doesn't take you right to the comment on first load. I had to focus the URL bar and hit enter for it to jump there.

The fix isn't publicly available unless you download 16.6 Preview

**Comment by DanRStevens** [comment]
Ahh yes, that comment. Unfortunately they didn't give any detail on what specifically was fixed, and if it requires any developer interaction. The link was just to a general product marketing page, nothing specific about the issue in question. I'm guessing they mean it won't warn about external libraries with a default out of the box install.

Anyway, I have a branch working now that silences the warning for the current version of the compiler.
